# Generated by Django 4.2.1 on 2023-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('storage_class', models.CharField(choices=[('STANDARD', 'STANDARD'), ('DEEP_ARCHIVE', 'DEEP_ARCHIVE')], max_length=32)),
            ],
        ),
    ]
